### ISSUE TITLE
Unable to remove ASD-node

### ISSUE THREAD

**Issue by simonOpenV** [openvstorage/framework-alba-plugin#561] opened 2018-02-07 10:07 UTC
### Problem description
Could not remove ASD node from the GUI when no asds were claimed. Only disks were initialzed

Asd manager log:
```
Feb 07 11:04:31 kvh195-5 python[30841]: Traceback (most recent call last):
Feb 07 11:04:31 kvh195-5 python[30841]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/api/decor
Feb 07 11:04:31 kvh195-5 python[30841]:     return_data = f(*args, **kwargs)
Feb 07 11:04:31 kvh195-5 python[30841]:   File "/opt/asd-manager/source/app/api.py", line 240, in clear_s
Feb 07 11:04:31 kvh195-5 python[30841]:     raise HttpNotAcceptableException(error='disk_not_configured',
Feb 07 11:04:31 kvh195-5 python[30841]: HttpNotAcceptableException: Status code: 406 - Error: disk_not_co


```

Plugin log:
```
Feb 07 11:04:31 kvh195-1 celery[31449]: 2018-02-07 11:04:31 31200 +0100 - kvh195-1 - 31449/14067077657984
0 - celery/log.py - log - 290 - ERROR - Task albanode.remove_node[4dce9a30-d2e3-4cb8-a019-4b14e4efa61e] r
aised unexpected: RuntimeError(u"Status code: 406 - Error: disk_not_configured'.",)
Feb 07 11:04:31 kvh195-1 celery[31449]: Traceback (most recent call last):
Feb 07 11:04:31 kvh195-1 celery[31449]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", li
ne 240, in trace_task
Feb 07 11:04:31 kvh195-1 celery[31449]:     R = retval = fun(*args, **kwargs)
Feb 07 11:04:31 kvh195-1 celery[31449]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", li
ne 438, in __protected_call__
Feb 07 11:04:31 kvh195-1 celery[31449]:     return self.run(*args, **kwargs)
Feb 07 11:04:31 kvh195-1 celery[31449]:   File "/opt/OpenvStorage/ovs/lib/albanode.py", line 109, in remo
ve_node
Feb 07 11:04:31 kvh195-1 celery[31449]:     AlbaNodeController.remove_slot(node_guid=node.guid, slot_id=s
lot_id)
Feb 07 11:04:31 kvh195-1 celery[31449]:   File "/usr/lib/python2.7/dist-packages/celery/local.py", line 1
88, in __call__
Feb 07 11:04:31 kvh195-1 celery[31449]:     return self._get_current_object()(*a, **kw)
Feb 07 11:04:31 kvh195-1 celery[31449]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", li
ne 439, in __protected_call__
Feb 07 11:04:31 kvh195-1 celery[31449]:     return orig(self, *args, **kwargs)
Feb 07 11:04:31 kvh195-1 celery[31449]:   File "/usr/lib/python2.7/dist-packages/celery/app/task.py", lin
e 420, in __call__
Feb 07 11:04:31 kvh195-1 celery[31449]:     return self.run(*args, **kwargs)
Feb 07 11:04:31 kvh195-1 celery[31449]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 46
1, in new_function
Feb 07 11:04:31 kvh195-1 celery[31449]:     output = f(*args, **kwargs)
Feb 07 11:04:31 kvh195-1 celery[31449]:   File "/opt/OpenvStorage/ovs/lib/albanode.py", line 237, in remo
ve_slot
Feb 07 11:04:31 kvh195-1 celery[31449]:     node.client.clear_slot(slot_id)
Feb 07 11:04:31 kvh195-1 celery[31449]:   File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", 
line 182, in clear_slot
Feb 07 11:04:31 kvh195-1 celery[31449]:     return self._call(requests.delete, 'slots/{0}'.format(slot_id
))
Feb 07 11:04:31 kvh195-1 celery[31449]:   File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", 
line 89, in _call
Feb 07 11:04:31 kvh195-1 celery[31449]:     raise RuntimeError(error_message)
Feb 07 11:04:31 kvh195-1 celery[31449]: RuntimeError: Status code: 406 - Error: disk_not_configured'
```

**Comment by JeffreyDevloo** [comment] 2018-02-07 10:17
Please branch off from Master. The recent promote might have caused this issue

**Comment by JeffreyDevloo** [comment] 2018-02-07 11:02
Duplicate of https://github.com/openvstorage/framework-alba-plugin/issues/558

**Closed by JeffreyDevloo** 2018-02-07 11:02 UTC
Labels: type_bug
