### ISSUE TITLE
The role check when adding a backend does not refresh

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework-alba-plugin#541] opened 2017-12-12 08:40 UTC
When having the 'Add Backend' wizard open without having a DB role assigned to any StorageRouter, the role check in the wizard will fail and not allow to add a Backend. When adding a DB role via the API or any other way without closing the 'Add Backend' wizard, the check does not refresh

**Comment by wimpers** [comment] 2017-12-21 09:41
Duplicate of https://github.com/openvstorage/framework/issues/1866

**Closed** 2017-12-21 09:43 UTC
Labels: priority_minor, process_duplicate, type_bug
