### ISSUE TITLE
System cannot handle old asd-managers

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework-alba-plugin#262] opened 2016-11-04 14:59 UTC
To be investigated.

After restart of asd-manager, they all turn green, however when trying to remove an asd ... the wizard keeps loading while calculating disk safety ...

**Comment by khenderick** [comment] 2016-11-04 15:08
New format:

```
In [9]: n.client.get_asds()
Out[9]: 
{u'/dev/disk/by-id/scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV5886907-part1': {u'C89YIdx2RMkLCIzIwl3zmIODkZHZFROD': {u'asd_id': u'C89YIdx2RMkLCIzIwl3zmIODkZHZFROD',
   u'capacity': 999713665024,
   u'home': u'/mnt/alba-asd/IDNvwJ5aoeQJfnOI/C89YIdx2RMkLCIzIwl3zmIODkZHZFROD',
   u'log_level': u'info',
   u'node_id': u'oZZGbkNuPNrUDsM1GhnJJopJlrNSnMPO',
   u'port': 8600,
   u'rocksdb_block_cache_size': 244070719,
   u'state': u'ok',
   u'transport': u'tcp'}},
 u'/dev/disk/by-id/scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV6612451-part1': {u'oW4lQgdes45Fd4464024jYjCUndE3rF0': {u'asd_id': u'oW4lQgdes45Fd4464024jYjCUndE3rF0',
   u'capacity': 999713665024,
   u'home': u'/mnt/alba-asd/AH1mcpRX45Apnb45/oW4lQgdes45Fd4464024jYjCUndE3rF0',
   u'log_level': u'info',
   u'node_id': u'oZZGbkNuPNrUDsM1GhnJJopJlrNSnMPO',
   u'port': 8601,
   u'rocksdb_block_cache_size': 244070719,
   u'state': u'ok',
   u'transport': u'tcp'}}}

In [11]: n.client.get_disks()
Out[11]: 
{u'scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV5886907': {u'aliases': [u'/dev/disk/by-id/scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV5886907',
   u'/dev/disk/by-path/pci-0000:03:00.0-sas-0x5000c292abb3645a-lun-0'],
  u'available': False,
  u'device': u'/dev/sdc',
  u'mountpoint': u'/mnt/alba-asd/IDNvwJ5aoeQJfnOI',
  u'node_id': u'oZZGbkNuPNrUDsM1GhnJJopJlrNSnMPO',
  u'partition_aliases': [u'/dev/disk/by-id/scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV5886907-part1',
   u'/dev/disk/by-path/pci-0000:03:00.0-sas-0x5000c292abb3645a-lun-0-part1'],
  u'partition_amount': 1,
  u'state': u'ok',
  u'state_detail': u'',
  u'usage': {u'available': 999601061888,
   u'size': 999713665024,
   u'used': 112603136}},
 u'scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV6612451': {u'aliases': [u'/dev/disk/by-id/scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV6612451',
   u'/dev/disk/by-path/pci-0000:03:00.0-sas-0x5000c294c5a0ee19-lun-0'],
  u'available': False,
  u'device': u'/dev/sdb',
  u'mountpoint': u'/mnt/alba-asd/AH1mcpRX45Apnb45',
  u'node_id': u'oZZGbkNuPNrUDsM1GhnJJopJlrNSnMPO',
  u'partition_aliases': [u'/dev/disk/by-id/scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV6612451-part1',
   u'/dev/disk/by-partlabel/scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-W',
   u'/dev/disk/by-path/pci-0000:03:00.0-sas-0x5000c294c5a0ee19-lun-0-part1'],
  u'partition_amount': 1,
  u'state': u'ok',
  u'state_detail': u'',
  u'usage': {u'available': 999601061888,
   u'size': 999713665024,
   u'used': 112603136}}}
```

Old format:

```
In [5]: n.client.get_asds()
Out[5]: 
{u'scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV5886907': {u'C89YIdx2RMkLCIzIwl3zmIODkZHZFROD': {u'asd_id': u'C89YIdx2RMkLCIzIwl3zmIODkZHZFROD',
   u'capacity': 999713665024,
   u'home': u'/mnt/alba-asd/IDNvwJ5aoeQJfnOI/C89YIdx2RMkLCIzIwl3zmIODkZHZFROD',
   u'log_level': u'info',
   u'node_id': u'oZZGbkNuPNrUDsM1GhnJJopJlrNSnMPO',
   u'port': 8600,
   u'rocksdb_block_cache_size': 244070719,
   u'state': u'ok',
   u'transport': u'tcp'}},
 u'scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV6612451': {u'oW4lQgdes45Fd4464024jYjCUndE3rF0': {u'asd_id': u'oW4lQgdes45Fd4464024jYjCUndE3rF0',
   u'capacity': 999713665024,
   u'home': u'/mnt/alba-asd/AH1mcpRX45Apnb45/oW4lQgdes45Fd4464024jYjCUndE3rF0',
   u'log_level': u'info',
   u'node_id': u'oZZGbkNuPNrUDsM1GhnJJopJlrNSnMPO',
   u'port': 8601,
   u'rocksdb_block_cache_size': 244070719,
   u'state': u'ok',
   u'transport': u'tcp'}}}

In [4]: n.client.get_disks()
Out[4]: 
{u'scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV5886907': {u'available': False,
  u'device': u'/dev/disk/by-id/scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV5886907',
  u'mountpoint': u'/mnt/alba-asd/IDNvwJ5aoeQJfnOI',
  u'name': u'scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV5886907',
  u'node_id': u'oZZGbkNuPNrUDsM1GhnJJopJlrNSnMPO',
  u'state': u'ok'},
 u'scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV6612451': {u'available': False,
  u'device': u'/dev/disk/by-id/scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV6612451',
  u'mountpoint': u'/mnt/alba-asd/AH1mcpRX45Apnb45',
  u'name': u'scsi-1ATA_WDC_WD1002FBYS-02A6B0_WD-WMATV6612451',
  u'node_id': u'oZZGbkNuPNrUDsM1GhnJJopJlrNSnMPO',
  u'state': u'ok'}}
```

**Comment by khenderick** [comment] 2016-11-07 09:12
Fixed by #266, packaged in openvstorage-backend-1.7.5-rev.809.4a885f8

**Comment by khenderick** [comment] 2016-11-07 09:14
Information for QA:
* Install 2.7.3 Fargo
* Upgrade to 2.7.4 Fargo (but somehow prevent the asd-manager from being restarted by the upgrade)
* Backend detail page should not show errors related to the update

**Comment by JeffreyDevloo** [comment] 2016-11-14 10:36
### Information
This issue comes forth from a bug where the asd-manager wasn't restarted after an update.
The issue that started this is https://github.com/openvstorage/alba-asdmanager/issues/146 and has been fixed.
Will try to reproduce this with the following steps:
- Stop asd-manager
- Replace executable by dummy proces
- Start dummy proces
- Start the real asd-manager in a screen
- Run update code (should restart the dummy process)

**Comment by JeffreyDevloo** [comment] 2016-11-14 12:34
### Information
Seeing as the origin of the issue is closed, I will close this one as well.
The backwards compatibility would have never been seen otherwise.

**Closed by JeffreyDevloo** 2016-11-14 12:34 UTC
Labels: priority_urgent, state_verification, type_bug
